In [5]:
import pandas as pd
import numpy as np

In [35]:
dict1={'Name':['Ajay','Gango3','Moksha',np.nan],
       'Age':[20,24,np.nan,26],'City':[np.nan,'Hyd','KMR','DBK']}

In [37]:
data=pd.DataFrame(dict1)
data

     Name   Age City
0    Ajay  20.0  NaN
1  Gango3  24.0  Hyd
2  Moksha   NaN  KMR
3     NaN  26.0  DBK

In [31]:
data.isnull()

    Name    Age   City
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

In [39]:
dict1={'Name':['Ajay','Gango3','Moksha',np.nan],
       'Age':[20,24,np.nan,26],'City':[np.nan,'Hyd','KMR','DBK'],
      'Company':['Google','Microsoft','Apple','Meta']}
data1=pd.DataFrame(dict1)
data1

     Name   Age City    Company
0    Ajay  20.0  NaN     Google
1  Gango3  24.0  Hyd  Microsoft
2  Moksha   NaN  KMR      Apple
3     NaN  26.0  DBK       Meta

**fillna**

In [46]:
data1.fillna(20)

     Name   Age City    Company
0    Ajay  20.0   20     Google
1  Gango3  24.0  Hyd  Microsoft
2  Moksha  20.0  KMR      Apple
3      20  26.0  DBK       Meta

In [48]:
#firat select the column
# then apply fill na
data1['Name'].fillna('Manish')

0      Ajay
1    Gango3
2    Moksha
3    Manish
Name: Name, dtype: object

**Draw back: Filling with Random value is not a Good approach**

- To avoid the we have some methods
    - backfill
    - bfill
    - ffill
    - pad

**pad**

In [52]:
data1.fillna(method='pad')

C:\Users\kkali\AppData\Local\Temp\ipykernel_8516\116358274.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1.fillna(method='pad')

     Name   Age City    Company
0    Ajay  20.0  NaN     Google
1  Gango3  24.0  Hyd  Microsoft
2  Moksha  24.0  KMR      Apple
3  Moksha  26.0  DBK       Meta

In [54]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='pad')

     Name   Age City    Company
0    Ajay  20.0  NaN     Google
1  Gango3  24.0  Hyd  Microsoft
2  Moksha  24.0  KMR      Apple
3  Moksha  26.0  DBK       Meta

In [56]:
import warnings
warnings.filterwarnings('ignore')
data1.fillna(method='pad',axis=1)

     Name     Age  City    Company
0    Ajay    20.0  20.0     Google
1  Gango3    24.0   Hyd  Microsoft
2  Moksha  Moksha   KMR      Apple
3     NaN    26.0   DBK       Meta

In [60]:
import warnings
warnings.filterwarnings('ignore')
data1.backfill()

     Name   Age City    Company
0    Ajay  20.0  Hyd     Google
1  Gango3  24.0  Hyd  Microsoft
2  Moksha  26.0  KMR      Apple
3     NaN  26.0  DBK       Meta

In [62]:
import warnings
warnings.filterwarnings('ignore')
data1.bfill()

     Name   Age City    Company
0    Ajay  20.0  Hyd     Google
1  Gango3  24.0  Hyd  Microsoft
2  Moksha  26.0  KMR      Apple
3     NaN  26.0  DBK       Meta

In [64]:
import warnings
warnings.filterwarnings('ignore')
data1.ffill()

     Name   Age City    Company
0    Ajay  20.0  NaN     Google
1  Gango3  24.0  Hyd  Microsoft
2  Moksha  24.0  KMR      Apple
3  Moksha  26.0  DBK       Meta

In [66]:
import warnings
warnings.filterwarnings('ignore')
data1.pad()

     Name   Age City    Company
0    Ajay  20.0  NaN     Google
1  Gango3  24.0  Hyd  Microsoft
2  Moksha  24.0  KMR      Apple
3  Moksha  26.0  DBK       Meta

**Mean-Median-Mode**

In [69]:
#step-1: Select the column
#step-2: get the mean
#step-3: apply fill na

age_mean=data1['Age'].mean()
print('age_mean',age_mean)
data1['Age'].fillna(age_mean)

age_mean 23.333333333333332

0    20.000000
1    24.000000
2    23.333333
3    26.000000
Name: Age, dtype: float64

In [71]:
city_mode=data1['City'].mode()
print('city_mode',city_mode)
data1['City'].fillna(city_mode)

city_mode 0    DBK
1    Hyd
2    KMR
Name: City, dtype: object

0    DBK
1    Hyd
2    KMR
3    DBK
Name: City, dtype: object

In [81]:
age_mean   #fixed value

np.float64(23.333333333333332)

In [83]:
city_mode   #series

0    DBK
1    Hyd
2    KMR
Name: City, dtype: object

In [89]:
import numpy as snp
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(X)

     0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [91]:
import numpy as snp
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,weights='uniform')
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [93]:
import numpy as snp
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,weights='distance')
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])