**EDA**

 **1.Data preprocess**

        - missing value analysis

        - data types mismatch

 **2. Data analysis**

        - Categorical

        - Numerical

        - Bi variate

        - Multivariate

        - Outlier analysis

 **3. Feture Engineering**

        - Impute the outlier

        - ML needs numbers, English to numbers: Encoding

        - Scaling: Standardization and Normalisation

        - Transformation: Convert into Normal distribution

In [3]:
import pandas as pd

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
visa_df=pd.read_csv(r"C:\Users\kkali\Documents\NOTES\Visadataset.csv")

In [9]:
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [11]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

**Case status**

In [14]:
# Step-1: find how many unique lables are there
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [16]:
# Step-2: creating a dictionary
d={'Certified':0,'Denied':1}
d

{'Certified': 0, 'Denied': 1}

In [24]:
# Step-3
visa_df['case_status']=visa_df['case_status'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,NaN
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,NaN
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,NaN
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,NaN
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,NaN
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,NaN
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,NaN
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,NaN
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,NaN

In [28]:
#read data again
visa_df=pd.read_csv(r"C:\Users\kkali\Documents\NOTES\Visadataset.csv")
visa_df['case_status'].unique()
d={'Certified':0,'Denied':1}
visa_df['case_status']=visa_df['case_status'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [36]:
visa_df=pd.read_csv(r"C:\Users\kkali\Documents\NOTES\Visadataset.csv")
visa_df['continent'].unique()
d={}

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [60]:
labels=visa_df['continent'].unique()
d={}
for i in range(len(labels)):
    d[labels[i]]=i
d

{np.int64(1): 0,
 np.int64(0): 1,
 np.int64(3): 2,
 np.int64(2): 3,
 np.int64(5): 4,
 np.int64(4): 5}

In [62]:
visa_df=pd.read_csv(r"C:\Users\kkali\Documents\NOTES\Visadataset.csv")
labels=sorted(visa_df['continent'].unique())
d={labels[i]:i for i in range(len(labels))}
visa_df['continent']=visa_df['continent'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [78]:
visa_df=pd.read_csv(r"C:\Users\kkali\Documents\NOTES\Visadataset.csv")
for i in cat[1:]:
    labels=sorted(visa_df[i].unique())
    d={labels[i]:i for i in range(len(labels))}
    visa_df[i]=visa_df[i].map(d)

visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

- sklean aka scikit-learn

    - preprocessing

       - labelEncoder
     
- **Step-1:** Import the module

- **step-2:** Save the module

- **step-3:** Apply filt_transform

       - fitting means creating a dictionary

       - transfor means apply dictionary so that data will be transformed

In [81]:
#Read data again
visa_df=pd.read_csv(r"C:\Users\kkali\Documents\NOTES\Visadataset.csv")

In [91]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['case_status']=le.fit_transform(visa_df['case_status'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [93]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['continent']=le.fit_transform(visa_df['continent'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [97]:
le.inverse_transform(visa_df['continent'])[:5]

array(['Asia', 'Asia', 'Asia', 'Asia', 'Africa'], dtype=object)

In [99]:
visa_df=pd.read_csv(r"C:\Users\kkali\Documents\NOTES\Visadataset.csv")
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:
    visa_df[i]=le.fit_transform(visa_df[i])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**OneHotEncoder**

- OneHot means at a time one will be ON(1) another will be OFF(0)

|case_staus|case_status_Denied|case_staus_Certified
|-|-|-|
|Denied|1|0
|certified|0|1
|certified|0|1
|Denied|1|0

In [102]:
visa_df=pd.read_csv(r"C:\Users\kkali\Documents\NOTES\Visadataset.csv")

In [108]:
pd.get_dummies(visa_df,columns=cat[1:],dtype=int)

,case_id,no_of_employees,yr_of_estab,prevailing_wage,continent_Africa,continent_Asia,continent_Europe,continent_North America,continent_Oceania,continent_South America,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,EZYV01,14513,2007,592.2029,0,1,0,0,0,0,...,0,1,1,0,0,0,0,1,0,1
1,EZYV02,2412,2002,83425.6500,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
2,EZYV03,44444,2008,122996.8600,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
3,EZYV04,98,1897,83434.0300,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
4,EZYV05,1082,2005,149907.3900,1,0,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,2601,2008,77092.5700,0,1,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
25476,EZYV25477,3274,2006,279174.7900,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
25477,EZYV25478,1121,1910,146298.8500,0,1,0,0,0,0,...,1,0,0,0,0,1,1,0,1,0
25478,EZYV25479,1918,1887,86154.7700,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,1,0
25479,EZYV25480,3195,1960,70876.9100,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0

**LabelEncoder vs OneHotEncoder**

- Generally we dont want a relationship between input columns

- we need both input columns are **not correlated** each other

- we need both input columns are **independent(x,y)** each other

- we need both input columns are **Perdencicular** each other

- we need both input columns are **Orthogonal** each other

- we need both input columns are **90 degrees phase shift** each other

- OneHotEncoder will achieve all the above

- But OneHotEncoder creates new columns

   - Columns are increase means dimenssions are increase

   - More dimension data need more processing time

   - More dimension data need more infra(like tpu)

   - This is called **Curse of Dimensionality**