In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
bank_df=pd.read_csv(r"C:\Naresh IT subject pdfs\bank.csv",sep=';')

In [ ]:
- shape

- size

- len

- columns

- dtypes

-isnull

-info

In [19]:
bank_df=pd.read_csv(r"C:\Naresh IT subject pdfs\bank.csv",sep=';')
df=pd.DataFrame()
df.shape

(0, 0)

In [21]:
bank_df=pd.read_csv(r"C:\Naresh IT subject pdfs\bank.csv",sep=';')
df=pd.DataFrame()
df.size

0

In [29]:
bank_df=pd.read_csv(r"C:\Naresh IT subject pdfs\bank.csv",sep=';')
df=pd.DataFrame(bank_df)
df.len

AttributeError: 'DataFrame' object has no attribute 'len'

In [3]:
visa_df=pd.read_csv(r"C:\Users\kkali\Documents\NOTES\Visadataset.csv")

NameError: name 'pd' is not defined

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
visa_df=pd.read_csv(r"C:\Users\kkali\Documents\NOTES\Visadataset.csv")

In [9]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [13]:
type(visa_df)

pandas.core.frame.DataFrame

In [15]:
type(visa_df.dtypes)

pandas.core.series.Series

- Series looks like dataframe(rows and columns) 

- dataframes has column names matrix kind

- series only index and its value # like key-value pair

- Series like a dictionary key and values

In [20]:
visa_df.dtypes.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [24]:
visa_df.dtypes.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [28]:
list(visa_df.dtypes.items())

[('case_id', dtype('O')),
 ('continent', dtype('O')),
 ('education_of_employee', dtype('O')),
 ('has_job_experience', dtype('O')),
 ('requires_job_training', dtype('O')),
 ('no_of_employees', dtype('int64')),
 ('yr_of_estab', dtype('int64')),
 ('region_of_employment', dtype('O')),
 ('prevailing_wage', dtype('float64')),
 ('unit_of_wage', dtype('O')),
 ('full_time_position', dtype('O')),
 ('case_status', dtype('O'))]

**Make a dataframes**

In [33]:
pd.DataFrame(visa_df.dtypes)

                             0
case_id                 object
continent               object
education_of_employee   object
has_job_experience      object
requires_job_training   object
no_of_employees          int64
yr_of_estab              int64
region_of_employment    object
prevailing_wage        float64
unit_of_wage            object
full_time_position      object
case_status             object

In [41]:
pd.DataFrame(visa_df.dtypes)

                             0
case_id                 object
continent               object
education_of_employee   object
has_job_experience      object
requires_job_training   object
no_of_employees          int64
yr_of_estab              int64
region_of_employment    object
prevailing_wage        float64
unit_of_wage            object
full_time_position      object
case_status             object

In [47]:
keys=visa_df.dtypes.keys()
values=visa_df.dtypes.values
pd.DataFrame(zip(keys,values),columns=['Column name','Data types'])

              Column name Data types
0                 case_id     object
1               continent     object
2   education_of_employee     object
3      has_job_experience     object
4   requires_job_training     object
5         no_of_employees      int64
6             yr_of_estab      int64
7    region_of_employment     object
8         prevailing_wage    float64
9            unit_of_wage     object
10     full_time_position     object
11            case_status     object

- When we have a dictionary 

- first makes in to keys and values seperate

- then create a dataframe

**Task-1: Seperate categorical columns and numerical columns**

In [51]:
dict1={'A':1,'B':2,'a':3,'b':4}
for i in dict1:
    print(i)

A
B
a
b

In [57]:
dict1={'A':1,'B':2,'a':3,'b':4}
for i,j in dict1.items():
    print(i,j)

A 1
B 2
a 3
b 4

In [59]:
dict1={'A':1,'B':2,'a':3,'b':4}
for i,j in dict1.items():
    if i.isupper():
        print(j)

1
2

In [99]:
dtypes=dict(visa_df.dtypes)
# iterate two i,j
# apply the condition
# if j=='object'
#append i in a list
# else
# append i in list
cat,num=[],[]
for i,j in dtypes.items():
    if j=='object':
        cat.append(i)
    else:
        num.append(i)

print(cat,num)

['case_id', 'continent', 'education_of_employee', 'has_job_experience', 'requires_job_training', 'region_of_employment', 'unit_of_wage', 'full_time_position', 'case_status'] ['no_of_employees', 'yr_of_estab', 'prevailing_wage']

In [103]:
dtypes=dict(visa_df.dtypes)
cat=[i for i,j in dtypes.items() if j=='object']
num=[j for i,j in dtypes.items() if j!='object']
print(cat,num)

['case_id', 'continent', 'education_of_employee', 'has_job_experience', 'requires_job_training', 'region_of_employment', 'unit_of_wage', 'full_time_position', 'case_status'] [dtype('int64'), dtype('int64'), dtype('float64')]

**Select_dtypes**

In [108]:
visa_df.select_dtypes(include='object').columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [110]:
visa_df.select_dtypes(exclude='object').columns

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

**Data Selection**

  - take

  - loc

  - iloc

In [121]:
visa_df.take([100,200,300],axis=0)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [135]:
cols=[1,5]
visa_df.take(cols,axis=1).take([100,200,300],axis=0)

    continent  no_of_employees
100      Asia             2227
200      Asia             3282
300      Asia             3268

**Drawbaks in take**

- manual counting index of columns

- at a time i can not select rows and columns need to do two takes

**iloc**

iloc[rows,columns]

iloc[star:stop:step,start:stop:step]

In [140]:
visa_df.iloc[1:5,2:5]

  education_of_employee has_job_experience requires_job_training
1              Master's                  Y                     N
2            Bachelor's                  N                     Y
3            Bachelor's                  N                     N
4              Master's                  Y                     N

In [144]:
visa_df.iloc[1:5,5]
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [146]:
visa_df.iloc[4,2:5]

education_of_employee    Master's
has_job_experience              Y
requires_job_training           N
Name: 4, dtype: object

In [148]:
visa_df.iloc[1:5,[2,6,7]]

  education_of_employee  yr_of_estab region_of_employment
1              Master's         2002            Northeast
2            Bachelor's         2008                 West
3            Bachelor's         1897                 West
4              Master's         2005                South

In [150]:
visa_df.iloc[[100,200,300],2:5]

    education_of_employee has_job_experience requires_job_training
100              Master's                  Y                     N
200             Doctorate                  Y                     N
300              Master's                  Y                     N

In [152]:
visa_df.iloc[[100,200,300],[2,6,7]]

    education_of_employee  yr_of_estab region_of_employment
100              Master's         2007            Northeast
200             Doctorate         1979                 West
300              Master's         2012              Midwest

In [156]:
print(visa_df.iloc[100,5])

2227

In [158]:
visa_df.iloc[100]

case_id                    EZYV101
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2227
yr_of_estab                   2007
region_of_employment     Northeast
prevailing_wage           28243.79
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 100, dtype: object

In [164]:
#selecting a particular column
visa_df.iloc[:,5]

0        14513
1         2412
2        44444
3           98
4         1082
         ...
25475     2601
25476     3274
25477     1121
25478     1918
25479     3195
Name: no_of_employees, Length: 25480, dtype: int64

In [162]:
visa_df.iloc[5,:]

case_id                     EZYV06
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2339
yr_of_estab                   2012
region_of_employment         South
prevailing_wage           78252.14
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 5, dtype: object

In [172]:
visa_df.iloc[:,[5]]  # dataframe

       no_of_employees
0                14513
1                 2412
2                44444
3                   98
4                 1082
...                ...
25475             2601
25476             3274
25477             1121
25478             1918
25479             3195

[25480 rows x 1 columns]

In [170]:
visa_df.iloc[[:,5]]  #series

SyntaxError: invalid syntax (3726906512.py, line 1)

In [176]:
visa_df.iloc[:,'no_of_employees']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

** Drawbacks in iloc**

- manual counting

In [179]:
visa_df.loc[:,'no_of_employees']

0        14513
1         2412
2        44444
3           98
4         1082
         ...
25475     2601
25476     3274
25477     1121
25478     1918
25479     3195
Name: no_of_employees, Length: 25480, dtype: int64

In [183]:
visa_df.loc[1:5,'no_of_employees']

1     2412
2    44444
3       98
4     1082
5     2339
Name: no_of_employees, dtype: int64

In [185]:
visa_df.loc[4,2:'education_of_employee']

TypeError: cannot do slice indexing on Index with these indexers [2] of type int

In [187]:
visa_df.loc[1:5,['education_of_employee']]

  education_of_employee
1              Master's
2            Bachelor's
3            Bachelor's
4              Master's
5              Master's

In [189]:
visa_df.loc[[100,200,300],:]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [191]:
visa_df.loc[[100,200,300],['education_of_employee']]

    education_of_employee
100              Master's
200             Doctorate
300              Master's

In [193]:
visa_df.loc[100,'education_of_employee']

"Master's"

In [195]:
visa_df.loc[100]

case_id                    EZYV101
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2227
yr_of_estab                   2007
region_of_employment     Northeast
prevailing_wage           28243.79
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 100, dtype: object

In [197]:
visa_df.loc[:'education_of_employee']

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [199]:
visa_df.loc[5,:]

case_id                     EZYV06
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2339
yr_of_estab                   2012
region_of_employment         South
prevailing_wage           78252.14
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 5, dtype: object